### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by lolminerxmrig** [0xKayala/NucleiScanner#1]
Hi.

![image](https://github.com/0xKayala/NucleiScanner/assets/108659226/b9285e82-fbe9-4ca8-b5b4-2b7f24668bab)

**Comment by 0xKayala** [comment]
Please check whether go is installed correctly or not and then install all the required tools individually and move them from go/bin/ to /usr/bin/ and whether all those tools are executing before you try `NucleiScanner`

**Comment by lolminerxmrig** [comment]
can send me telegram id?

**Comment by 0xKayala** [comment]
You can ping me on my twitter account: https://twitter.com/0xKayala
