### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Teicu** [0xKayala/NucleiScanner#2]
Hi, 
 
I tried to install it on my Mac but it doesn't work, any idea why? 

mv: fastcopy: open() failed (to): /usr/bin/ns: Operation not permitted
chmod: /usr/bin/ns: No such file or directory
NucleiScanner has been installed successfully! Now Enter the command 'ns' to run the tool.
➜  NucleiScanner ns
zsh: command not found: ns

**Comment by 0xKayala** [comment]
It looks like the /usr/bin/ path is different in your Mac, you need to find the relevant path and then follow the steps involved in `install.sh` file
