### ISSUE TITLE
 error reading config 

### ISSUE THREAD

**Issue by Ondrik8** [0xKayala/NucleiScanner#3]
WARN[0000] error reading config: open /home/rew/.gau.toml: no such file or directory

**Comment by 0xKayala** [comment]
Create `.gau.toml` file using `nano` on your home directory (home/kali/) and add the below code with your API key to resolve this issue.

**Reference:** https://raw.githubusercontent.com/lc/gau/master/.gau.toml

```
threads = 2
verbose = false
retries = 15
subdomains = false
parameters = false
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

[urlscan]
  apikey = ""

[filters]
  from = ""
  to = ""
  matchstatuscodes = []
  matchmimetypes = []
  filterstatuscodes = []
  filtermimetypes = ["image/png", "image/jpg", "image/svg+xml"]
```
