### ISSUE TITLE
how to install and use under ubuntu22.04

### ISSUE THREAD

**Issue by blieyao** [0xKayala/NucleiScanner#6]
Hello, how to install and use under ubuntu22.04, I used the Readm
![errr](https://github.com/user-attachments/assets/c984f82b-49d8-4a4e-beb9-80626dd7128e)
![u](https://github.com/user-attachments/assets/3cb94997-cb4e-4c85-b013-a213aaf0bca7)
e installation instructions to install failed

**Comment by 0xKayala** [comment]
Hi Bro,

Make sure you have installed go on your Linux os and update the nuclei tool and then follow the readme steps
